---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/crazy-task-tracker
    username: munirhasanov
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


